<!DOCTYPE html>
<html>
<body>

<h2>What Can JavaScript Do?</h2>

<p>JavaScript can change HTML attribute values.</p>

<p>In this case JavaScript changes the value of the src (source) attribute of an image.</p>

<button onclick="document.getElementById('myImage').src='file:///C:/Users/16304071/Desktop/tenor.gif'">Dog</button>

<img id="myImage" src="catdog.gif" style="width:100px">

<button onclick="document.getElementById('myImage').src='file:///C:/Users/16304071/Desktop/index.jfif'">Cat</button>

</body>
</html>
